[general]
framerate = 60
bars = 12
bar_width = 3
bar_spacing = 1

[input]
method = pulse # or pipewire
source = auto

[output]
method = raw
raw_target = /dev/stdout
data_format = ascii
ascii_max_range = 7