# brew-task Hyprland rules
windowrule = float on,   match:title ^(brew-task)$
windowrule = size 480 560, match:title ^(brew-task)$
windowrule = move (monitor_w-492) (monitor_h-598), match:title ^(brew-task)$
windowrule = pin on, match:title ^(brew-task)$
windowrule = suppress_event maximize, match:title ^(brew-task)$
windowrule = animation slide bottom, match:title ^(brew-task)$

layerrule = blur on, match:namespace brew-task 
layerrule = ignore_alpha 0.5, match:namespace brew-task 