#################
##  SOURCING  ##
#################

source = ~/.config/hypr/HLconfigs/monitors.conf
source = ~/.config/hypr/HLconfigs/myprograms.conf
source = ~/.config/hypr/HLconfigs/autostart.conf
source = ~/.config/hypr/HLconfigs/env.conf
source = ~/.config/hypr/HLconfigs/perm.conf
source = ~/.config/hypr/HLconfigs/lookandfeel.conf
source = ~/.config/hypr/HLconfigs/input.conf
source = ~/.config/hypr/HLconfigs/keybindings.conf
source = ~/.config/hypr/HLconfigs/windowsandworkspaces.conf
